accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), 
		name='login'),
	url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
	url(r'^signup/$', views.Signup.as_view(), name='signup'),
]

chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

chatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as base_views

from .import views


from accounts import urls as accounts_urls

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', base_views.HomePage.as_view(), name='home'),
    path('accounts/', include(accounts_urls)),
    path('detection/', views.DETECTION_PAGE, name='detection'), 
    path('detection_SVM/', views.DETECTION_PAGE_SVM, name='detection_SVM'), 

    path('info/', views.info, name='info'), 
    path('about_us/', views.about_us, name='about_us'), 
    path('display_result', views.display_result, name = 'display_result'),
    path('display_result_SVM', views.display_result_SVM, name = 'display_result_SVM'),


]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

	def __str__(self):
		return f"{self.username}"

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse


# Create your models here.
User = get_user_model()

class INPUT_IMAGES(models.Model): 
    Input = models.FileField(upload_to='static/images/') 

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
	fields = ("username", "password1", "password2")
	model = get_user_model()

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['username'].help_text = None		
		self.fields['password1'].help_text = None
		self.fields['password2'].help_text = None

chat/forms.py
from django import forms
from .models import INPUT_IMAGES


class INPUT_IMAGE_FORM(forms.ModelForm):   
    class Meta: 
        model = INPUT_IMAGES
        fields = ['Input'] 

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import CreateView

# Create your views here.
class Signup(CreateView):
	form_class = UserCreateForm
	success_url = reverse_lazy('accounts:login')
	template_name = 'accounts/signup.html'

chat/views.py
from django.views.generic import CreateView, ListView
from .forms import ChatForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Chat
from django.utils import timezone

from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from .forms import *


from django import template
# Create your views here.



class ChatCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    form_class = ChatForm
    model = Chat

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ChatListView(LoginRequiredMixin, ListView):
    model = Chat

    def get_queryset(self):
        return Chat.objects.filter(posted_at__lte=timezone.now()).order_by('posted_at')

chatApp/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse 
from chat.forms import *

# from neural_network.TESTING_CNN import get
import pyttsx3
import test

from neural_network.TESTING_SVM import get

import chatApp.test

class HomePage(TemplateView):
	template_name = 'index.html'

def info(request):
		return render(request, 'info.html')


def about_us(request):
		return render(request, 'about_us.html')


def DETECTION_PAGE(request):   
    if request.method == 'POST': 
        form = INPUT_IMAGE_FORM(request.POST, request.FILES) 
  
        if form.is_valid(): 
            form.save() 
            return redirect('display_result') 
    else: 
        form = INPUT_IMAGE_FORM() 
    return render(request, 'detection.html', {'form' : form}) 
  

def DETECTION_PAGE_SVM(request):   
    if request.method == 'POST': 
        form = INPUT_IMAGE_FORM(request.POST, request.FILES) 
  
        if form.is_valid(): 
            form.save() 
            return redirect('display_result_SVM') 
    else: 
        form = INPUT_IMAGE_FORM() 
    return render(request, 'detection_SVM.html', {'form' : form}) 


# def predicted_results(request):
# 		if request.method == 'GET':
# 			sym1 =request.GET['filename']
# 			print(sym1)
# 		return render(request, 'detect_result.html')

def display_result(request):   
        IMAGES = INPUT_IMAGES.objects.all()
        print('./' + str(IMAGES[len(IMAGES)-1].Input ))

        bt_result,prevention_action = 1,2

        bt_result = get('./' + str(IMAGES[len(IMAGES)-1].Input ))        


        return render(request, 'display_result.html', {'image':IMAGES[len(IMAGES)-1].Input ,'result':bt_result,'prevention_action':prevention_action})



def display_result_SVM(request):   
        IMAGES = INPUT_IMAGES.objects.all()
        print('./' + str(IMAGES[len(IMAGES)-1].Input ))

        bt_result,prevention_action = 1,2

        bt_result = get('./' + str(IMAGES[len(IMAGES)-1].Input ))        

        return render(request, 'display_result_SVM.html', {'image':IMAGES[len(IMAGES)-1].Input ,'result':bt_result,'prevention_action':prevention_action})

templates/about_us.html
{% extends "base.html" %}

{% block title %}
	About us
{% endblock title %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
                #customers {
                font-family: Arial, Helvetica, sans-serif;
                border-collapse: collapse;
                width: 100%;
                }
                
                #customers td, #customers th {
                border: 3px solid #ddd;
                padding: 8px;
                }
                

                

                #customers th:hover {background-color: #8edcf1c9;text-align: center;text}
                
                #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: center;
                background-color: #ba9958c9;
                color: white;
                }


</style>
</head>

<!-- <div class="row justify-content-center mt-15">
    <div class="col-md-20 text-center" text-align= "justify">

            <h1><u>
              About us
            </u></h1>
    </div>
</div>

<br>
<hr> -->
<div class="row justify-content-center mt-15">
  <div class="col-md-20 text-center" text-align= "justify">

          <h1><u>
            Bharati Vidyapeeth College of engineering
          </u></h1>
  </div>
</div>




<div class="row justify-content-center mt-15">
  <div class="col-md-20 text-center" text-align= "justify">
          <br><br>
          <img src="/static/img/Bharti_Vidyapeeth.jpeg" class="img-responsive" style="width: 75%; float: center; " />                
          <br><br><br>         
  </div>
</div>


<br>
<table id="customers">
  <!-- <tr>
    <th>Parameter</th>
    <th>Value</th>
  </tr> -->

  <tr>
    <th rowspan="3"> Members </th>
    <th> 1. Name 1 </th>
  </tr>
  
  <b>
  <tr>
    <th> 2. Name 2 </th>
  </tr>

  <tr>
    <th> 3. Name 3 </th>
  </tr>

  <tr>
    <td>  </td>
    <td>  </td>
  </tr>

  <tr>
    <th> Guide Name </th>
    <th> Prof. K.S. Warke </th>
  </tr>


  <tr>
    <td>  </td>
    <td>  </td>
  </tr>

  <tr>
    <th> IJCRT </th>
    <th><a href="https://ijcrt.org/viewfull.php?&p_id=IJCRT2405582" target="_blank">Link</a></th>

  </tr>



</table>




{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock title %}


{% block content %}


<div class="row justify-content-center mt-3">
	<div class="col-md-5">
		<h2>Login</h2>
	</div>
</div>


<br><br>

<div class="row justify-content-center mt-3">
	<div class="col-md-5">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<br>

			<input type="submit" value='Login' class="btn btn-lg btn-warning">
		</form>
		<br>
		<hr>
		<div class="text-center">
			Need an account? <a href="{% url 'accounts:signup' %}">Sign Up here</a>
		</div>

	</div>
</div>


{% endblock content %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block title %}

    Signup

{% endblock title %}

{% block content %}

<div class="row justify-content-center mt-3">
	<div class="col-md-5">
		<h2>Signup</h2>
	</div>
</div>


<br><br>

<div class="row justify-content-center mt-3">
	<div class="col-md-5">
			<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<br>
			<input type="submit" value='Signup' class="btn btn-lg btn-warning">
			</form>

            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'accounts:login' %}">Login here</a>
            </div>
			
	</div>
</div>

    <!-- <div class="row">
			<div class="col-md-4">
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value='Signup' class="btn btn-outline-primary">
				</form>
			</div>
			<div class="col-md-7">
				<h4>Be Ready To Become a Part Of System</h4><hr>
				<p class="description">
					Well, Hello and welcome to the System! 
				</p>
			</div>
		</div> -->

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

	<body style="background-color:rgb(198, 194, 176);"></body>

		
		<!-- Title -->
		<title>{% block title %} {% endblock title %}</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:wght@300;400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
		
		<!-- Style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

		<!-- Favicon -->
		<!-- <link rel="shortcut icon" type="image/svg" href="{% static 'favicon.svg' %}"> -->

		<!-- <link rel="icon" type="image/png"  href="{% static 'todo/logo.png' %}"> -->
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel="icon" type="image/png"  href="{% static 'logo.png' %}">

</head>

<body >

		<!-- Nav -->
		<!-- <nav class="navbar navbar sticky-top navbar-expand-lg navbar-dark" style="font-weight: 300; box-shadow: 0px 0px 5px px #000; font-family: 'Ubuntu', sans-serif;"> -->

			<nav class="navbar navbar sticky-top navbar-expand-lg navbar-dark" style="background-color:  #30529b; 
			font-weight: 300; box-shadow: 0px 0px 20px 5px #a09de3; font-family: 'Ubuntu', sans-serif;">
			
			{% if user.is_authenticated %}
				<a class="navbar-brand" href="{% url 'home' %}">Welcome, {{user}} </a>

			{% else %}
			<a class="navbar-brand" href="{% url 'home' %}">Classification </a>

			{% endif %}

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  {% if user.is_authenticated %}
		      
		      <div class="collapse navbar-collapse" id="navbarNav">
		        <ul class="navbar-nav">

		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'info' %}">Information <span class="sr-only">(current)</span></a>
		          </li>

		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'about_us' %}">About us <span class="sr-only">(current)</span></a>
		          </li>

		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'detection' %}">Classification using Neural Network<span class="sr-only">(current)</span></a>
		          </li>


		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'detection_SVM' %}">Classification using SVM<span class="sr-only">(current)</span></a>
		          </li>

				  
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
		          </li>

		        </ul>
		      </div>
		  
		  {% else %}
		  	<div class="collapse navbar-collapse" id="navbarNav">
		        <ul class="navbar-nav">
		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'info' %}">Information <span class="sr-only">(current)</span></a>
		          </li>
		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'about_us' %}">About us <span class="sr-only">(current)</span></a>
		          </li>

				  <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
		          </li>
		        </ul>
		      </div>
		  {% endif %}
		</nav>


		<!-- Content -->
		<div class="container" style="margin-top: 50px;">{% block content %}{% endblock content %}</div>
		<br><br><hr><br><br>





		<button onclick="topFunction()" id="go-to-top" title="Go to top">&#8593;</button>
		<script type="text/javascript">
			//Get the button:
			go_to_top = document.getElementById("go-to-top");

			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function() {scrollFunction()};

			function scrollFunction() {
			  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 200) {
			    go_to_top.style.display = "block";
			  } else {
			    go_to_top.style.display = "none";
			  }
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
			  document.body.scrollTop = 0; // For Safari
			  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
			}
		</script>
</body>
</html>

templates/chat/chat_form.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}

    	<br><input type="submit" value="Post" class="btn btn-lg btn-outline-primary">
    </form>
{% endblock content %}

templates/chat/chat_list.html
{% extends "base.html" %}

{% block title %}
    Chatting
{% endblock title %}

{% block content %}
    <a href="/chat"><button class="btn btn btn-primary"><i class="fa fa-refresh" aria-hidden="true"></i>
    Rerfresh For Any New Chats</button></a><br><br><br>

    {% for chat in object_list %}

    		{% if chat.user.is_superuser  %}                    
                {% if  user.get_username == chat.receiver  %}
            	    <div class="chat" style="width: 90%; background: rgb(127, 140, 80); box-shadow: 2px 0px 25px 20px #330;">    		    
    		            <small class="chat-user-special"> {{ chat.user }}  -> {{ chat.receiver }}      </small>
    		            <p><b class="chat-content">{{ chat|linebreaks }} </b></p>
    		            <small class="chat-date">{{ chat.posted_at }}</small>
            	    </div><br><br>    
                {% endif %}
    		
    		{% else %}
                {% if  user  ==  chat.user  and chat.receiver == 'admin' %}
                	<div class="chat" style="width: 90%; background: rgb(50, 40, 127); box-shadow: 2px 0px 25px 20px #000;text-align: right;">
    			    <small class="chat-user"> {{ chat.user }}  -> {{ chat.receiver }}  </small>    		    
    		        <p><b class="chat-content">{{ chat|linebreaks }}</b></p>
    		        <small class="chat-date">{{ chat.posted_at }}</small>
            		</div><br><br>    
                {% endif %}
    		{% endif %}

            {% if user.get_username == 'admin'%}
                        {% if  chat.user.get_username == 'admin'  %}
            	            <div class="chat" style="width: 90%; background: rgb(50, 40, 127); box-shadow: 2px 0px 25px 20px #330;text-align: right;">    		    
    		                    <small class="chat-user-special"> {{ chat.user }}  -> {{ chat.receiver }}      </small>
    		                    <p><b class="chat-content">{{ chat|linebreaks }} </b></p>
    		                    <small class="chat-date">{{ chat.posted_at }}</small>
            	            </div><br><br>    
                        {% endif %}
    		
                        {% if  chat.receiver == 'admin' %}
                	        <div class="chat" style="width: 90%; background: rgb(127, 140, 80); box-shadow: 2px 0px 25px 20px #000;">
    			            <small class="chat-user"> {{ chat.user }}  -> {{ chat.receiver }}  </small>    		    
    		                <p><b class="chat-content">{{ chat|linebreaks }}</b></p>
    		                <small class="chat-date">{{ chat.posted_at }}</small>
            		        </div><br><br>    
                        {% endif %}
            {% endif %}
    		

    {% empty %}
    <h1 class="heading">No Chats Yet Be The First To Message!</h1><br>

    {% endfor %}
    <br><a href="{% url 'chat:new' %}"><button class="btn btn-outline-primary">New Message</button></a>
{% endblock content %}

templates/detection.html
{% extends "base.html" %}

{% block title %}
	Classification
{% endblock title %}

{% block content %}

		    <h1 style="text-align: center;">Welcome {{ user }}, upload file to get result of Classification using Neural Network</h1><br><hr class="hr"><br><br>
			    <body> 
				<form method = "post" enctype="multipart/form-data"> 
					<div class="row justify-content-center mt-5">
						<div class="col-md-4 text-center" text-align= "justify">
	

								{% csrf_token %}    
								{{ form.as_p }}
								<br>
								<button type="submit"  class="btn btn-lg btn-warning">Upload File</button> 


						</div>
					</div>
	  
				</form> 
				</body> 

				  


{% endblock content %}

templates/detection_SVM.html
{% extends "base.html" %}

{% block title %}
	Classification
{% endblock title %}

{% block content %}

		    <h1 style="text-align: center;">Welcome {{ user }}, upload file to get result of Classification using SVM</h1><br><hr class="hr"><br><br>
			    <body> 
				<form method = "post" enctype="multipart/form-data"> 
					<div class="row justify-content-center mt-5">
						<div class="col-md-4 text-center" text-align= "justify">
	

								{% csrf_token %}    
								{{ form.as_p }}
								<br>
								<button type="submit"  class="btn btn-lg btn-warning">Upload File</button> 


						</div>
					</div>
	  
				</form> 
				</body> 

				  


{% endblock content %}

templates/display_result.html
{% extends "base.html" %}

{% block title %}
	Classification
{% endblock title %}

{% block content %}

<head>
	<style>
	.center {
	  line-height: 200px;
	  height: 60px;
	  border: 3px solid rgb(118, 170, 15);
	  text-align: center;
	}
	
	.center p {
	  line-height: 1.5;
	  display: inline-block;
	  vertical-align: middle;
	}
	</style>

<style>
	#customers {
	font-family: Arial, Helvetica, sans-serif;
	border-collapse: collapse;
	width: 100%;
	}
	

	#customers td, #customers th {
	border: 3px solid #16041f;
	padding: 8px;
	text-align: center;
	}
	
	#customers tr:nth-child(even){background-color: #deca91;text-align: center}
	#customers tr:nth-child(odd){background-color: #ddc366;text-align: center}
	#customers tr:hover {background-color: #f1f1f1;text-align: center;text;color: rgba(0, 0, 170, 0.858)}
	
	#customers th {
	padding-top: 12px;
	padding-bottom: 12px;
	text-align: center;
	background-color: rgba(226, 203, 176, 0.067);
	color: rgba(183, 9, 9, 0.858);
	}
	</style>



	</head>
	<div class="row justify-content-center mt-15">
		<div class="col-md-20 text-center" text-align= "justify">
			<br><br>
			<h2  style="text-align: center;"> Result of uploaded audio file using Neural Network is : </h2>
			<br><br><hr><br><br>
			<h1  style="text-align: center;color:red">  {{result}}  </h1>	
			
			<br>
				<br>
				<br>

		</div></div>


{% endblock content %}

templates/display_result_SVM.html
{% extends "base.html" %}

{% block title %}
	Classification
{% endblock title %}

{% block content %}

<head>
	<style>
	.center {
	  line-height: 200px;
	  height: 60px;
	  border: 3px solid rgb(118, 170, 15);
	  text-align: center;
	}
	
	.center p {
	  line-height: 1.5;
	  display: inline-block;
	  vertical-align: middle;
	}
	</style>

<style>
	#customers {
	font-family: Arial, Helvetica, sans-serif;
	border-collapse: collapse;
	width: 100%;
	}
	

	#customers td, #customers th {
	border: 3px solid #16041f;
	padding: 8px;
	text-align: center;
	}
	
	#customers tr:nth-child(even){background-color: #deca91;text-align: center}
	#customers tr:nth-child(odd){background-color: #ddc366;text-align: center}
	#customers tr:hover {background-color: #f1f1f1;text-align: center;text;color: rgba(0, 0, 170, 0.858)}
	
	#customers th {
	padding-top: 12px;
	padding-bottom: 12px;
	text-align: center;
	background-color: rgba(226, 203, 176, 0.067);
	color: rgba(183, 9, 9, 0.858);
	}
	</style>



	</head>
	<div class="row justify-content-center mt-15">
		<div class="col-md-20 text-center" text-align= "justify">
			<br><br>
			<h2  style="text-align: center;"> Result of uploaded audio file using SVM is : </h2>
			<br><br><hr><br><br>
			<h1  style="text-align: center;color:red">  {{result}}  </h1>	
			
			<br>
				<br>
				<br>

		</div></div>


{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block title %}
	Classification
{% endblock title %}

{% block content %}
{% load static %}


<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" type="text/css" href="{% static 'home_page_css .css' %}">

</head>



<div class="text-center">
	<br><br><br><br><br><br>
				<h1> <b> AI generated and manipulated voice detection  </b> </h1>

	</div>


	
				<div class="row justify-content-center ">
					<div class="text-center">
		
					 <br>
				<p style="text-align:justify;" >	
					<h2>
						With the rise of deepfake technology, which can generate synthetic voices that mimic real people, AI is also being used to detect manipulated or synthesized voices. These detection systems analyze subtle cues and inconsistencies in speech to identify artificially generated content.

						
					</h2>			
			</div>
		</div>
	
			

		<script>
			var myIndex = 0;
			carousel();
			
			function carousel() {
			  var i;
			  var x = document.getElementsByClassName("mySlides");
			  for (i = 0; i < x.length; i++) {
				x[i].style.display = "none";  
			  }
			  myIndex++;
			  if (myIndex > x.length) {myIndex = 1}    
			  x[myIndex-1].style.display = "block";  
			  setTimeout(carousel, 2500);    
			}
		</script>
					
			
{% endblock content %}